apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-project
  labels:
    app: django-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-project
        image: damodarvishw/django-project:new-api
        ports:
        - containerPort: 8000
